project_id = "vintehwihywdjqjtlpxi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/auth/update-password",
  "http://localhost:3001/auth/callback",
  "http://localhost:3001/auth/update-password",
  "http://localhost:3002/auth/callback",
  "http://localhost:3002/auth/update-password",
  "http://localhost:3003/auth/callback",
  "http://localhost:3003/auth/update-password",
  "https://excelify.co.in/auth/callback",
  "https://excelify.co.in/auth/update-password"
]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
